FEAT: Connection with Firebase
rolandkasa-95/DevBook pull request #2
Opened 2021-09-22 12:40 UTC by aciobotaruSV

2021-09-23 09:55 UTC, rolandkasa-95 requested changes

2021-09-23 09:55 UTC, rolandkasa-95 commented on src/App.js
> +            <AuthForm />
Make it a little cleaner, put the component call inside the route.

2021-09-23 09:55 UTC, rolandkasa-95 commented on src/App.js
> +            <Dashboard />
Same here.

2021-09-23 09:55 UTC, rolandkasa-95 commented on src/FireStoreData.js
> +const FireStoreData = (database) => {
Does this needs to be a fully fledged component?

2021-09-23 09:55 UTC, rolandkasa-95 commented on src/firebase.config.js
> +const firebaseConfig = {
Move the initialization to a service file.

2021-09-24 07:27 UTC, aciobotaruSV commented
Please review

2021-09-24 07:31 UTC, rolandkasa-95 approved these changes

2021-09-24 07:31 UTC, rolandkasa-95 commented on src/components/AuthForm/AuthForm.js
> +        console.log(user.email);
Remove console logs.

2021-09-24 07:31 UTC, rolandkasa-95 commented on src/components/AuthForm/AuthForm.js
> +  console.log(loggedIn);
Same here.

2021-09-24 07:31 UTC, merged